version: '3.8'

services:
  redis:
    image: redis:6-alpine
  web:
    build: ./app
    command: gunicorn fampay_assi.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.db.env
  celery:
    build: ./app
    command: celery -A fampay_assi worker -l info
    env_file:
      - .env
    depends_on:
      - db
      - web
      - redis
  celery-beat:
    build: ./app
    command: celery -A fampay_assi beat -l info
    env_file:
      - .env
    depends_on:
      - db
      - web
      - redis
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: