# Generated by Django 4.0 on 2021-12-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
