# Generated by Django 4.0 on 2021-12-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_video_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
