# Generated by Django 4.0 on 2021-12-19 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_url', models.URLField()),
                ('channel_id', models.CharField(max_length=30, unique=True)),
                ('channel_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='live_broadcast',
            field=models.CharField(choices=[('upcoming', 'upcoming'), ('live', 'live'), ('none', 'none')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='channel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.channel'),
            preserve_default=False,
        ),
    ]
